### PR TITLE
Chaimleib ashkenazi.po

### PR DESCRIPTION
**Pull request by chaimleib**
I see these spellings more often in US paper calendars and publications

### CODE REVIEW

**Comment by mjradwin** [comment]
Hebcal is 30 celebrating years in 2022, and I'm not sure we're ready for a massive renaming of transliterations, even if the rest of the Internet chooses to spell Chanukah differently. @dsadinoff do you think we should take some or all of these?

Thanks for the other (PR #233) cities pull request. That's a very good one and easy to accept.

**Comment by chaimleib** [comment]
Why the mention of Chanukah? I didn't change that spelling.

**Comment by chaimleib** [comment]
You're welcome for the cities.h additions! Glad to contribute!

**Comment by mjradwin** [comment]
I've merged some of these changes but am not able to take the other changes at this time.

**Pull request closed without merging**
