### PR TITLE
Litvish Rosh → Reish

### PR DESCRIPTION
**Pull request by yisraeldov**
Needs to be consistent for Cholem to always be "ei"

### CODE REVIEW

**Comment by yisraeldov** [comment]
@mjradwin any chance to get this merged ?

**Comment by yisraeldov** [comment]
@mjradwin Any reason not to merge this ?

**Comment by yisraeldov** [comment]
Thanks, was wondering what happened

**Comment by mjradwin** [comment]
Released in hebcal 4.17

**Pull request merged**
