### PR TITLE
Change dates to Julian for years prior to 1752

### PR DESCRIPTION
**Pull request by Isaac-D-Cohen**
I added/modified some code to change the dates to Julian prior to Sep. 14, 1752. I chose this because this is the default on ncal in Linux. That's the date when the British empire switched.

### CODE REVIEW

**Comment by Isaac-D-Cohen** [comment]
It looks like there are 7 commits in the pull request. But only 6 of them have to do with the Julian calendar thing. The first one is a commit from a different pull request that you merged a while ago. I'm not sure how that one got included here.

**Comment by mjradwin** [comment]
I saw that. Thanks. I may rework some of the `greg2abs` and `abs2greg` edits before merging to better preserve some of the line-level history in the files. We also really need some unit tests to make sure this doesn't break anything (and that it actually does what it's supposed to for years 1751, 1752 and 1753).

**Comment by Isaac-D-Cohen** [comment]
I checked and indeed it does brake something. If you type `hebcal 1752` it all works fine. But if you write `hebcal Tish 5513` it exits with an error. This happens because in the later years of the Julian calendar it was possible for Tishrei to begin really early, sometimes in August (Rosh Hashana 1752 was on August 29)! This breaks the search optimizer in common.c (around line 239) in the abs2hebrew function. Since gregdate.mm - 1 becomes 7, it maps the month to Tamuz making it the end of the year, so the heb2abs function subsequently obtains a higher value than the absolute date we already have (stored in d)!

There are two possible solutions to this:
1. We can change the range for the search optimizer to 5514-10666 instead of the current 4635-10666 (meaning it will only optimize under the gregorian calendar).
2. We can change Tamuz to Tishrei in the mmap array.

**Comment by Isaac-D-Cohen** [comment]
Someone suggested to me that I should make the adjustment date easily changeable, since the calendar was changed in different countries at different times. I figured I'd insert define statements in greg.h so anyone can easily modify the switch date in accordance with whichever country they want.

**Comment by mjradwin** [comment]
Unfortunately, I'm going to close this PR without merging it in. It's a very very good idea, and you'll see from issue #65 that a feature like this has been on the wishlist for nearly 20 years.

However, we recently completed a huge rewrite of the Hebcal command-line app in Go. The Go Programming Language includes modern features that we expect will make it easier to maintain than the 30-year-old C version. As such, this patch would need to be rewritten in Go as well.

**Pull request closed without merging**
